#Mystic Roles
#Alphabetical pwetty pwease
- type: playTimeTracker
  id: JobArchivist

- type: playTimeTracker
  id: JobChiefSecurityOfficer

- type: playTimeTracker
  id: JobDirector

- type: playTimeTracker
  id: JobDivinologist

- type: playTimeTracker
  id: JobMasterArcanist

- type: playTimeTracker
  id: JobMysticFledgling

- type: playTimeTracker
  id: JobMysticResearcher

- type: playTimeTracker
  id: JobLogisticsSpecialist

- type: playTimeTracker
  id: JobMysticQuartermaster

- type: playTimeTracker
  id: JobOSArcanaut

- type: playTimeTracker
  id: JobOSMarine

- type: playTimeTracker
  id: JobOSParamedic

- type: playTimeTracker
  id: JobOSTech

- type: playTimeTracker
  id: JobServiceLeader
